### PR TITLE
Remove incompatible & unused browser tests

### PR DESCRIPTION
**Pull request by mattnorris**
# Pull Request 

## Description

Remove IE11 tests and old, unused browser tests. 

Fixes https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-64534

## Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by taymoork2** [comment]
Missed two files
`packages/node_modules/@ciscospark/plugin-phone/browsers.js`
`packages/node_modules/@ciscospark/media-engine-webrtc/browsers.js`

**Comment by mattnorris** [comment]
@taymoork2 I was going to leave those because they have the latest FF instead of an arbitrary older one. They are commented out though for what I assume would be quick troubleshooting. Is that worth it to keep?

**Comment by taymoork2** [comment]
@mattnorris up to you, nothing changes if we keep it or remove it since they're already commented out

**Comment by mattnorris** [comment]
@taymoork2 let's keep them for now and reevaluate when we do a holistic review.

**Comment by taymoork2** [comment]
Asking this question for future reference

Why are we getting rid of IE tests on saucelabs?

**Comment by mattnorris** [comment]
Actually... we don't have to. There are problems when running them in development mode locally because they are not transpiled correctly by Babel on-the-fly. But when transpiled to `dist` they do work for the most part. 

I'll reference these commits later when cleaning up the available browsers we actually don't test on.

**Comment by mattnorris** [comment]
Resurrecting after our conversation at standup.

**Pull request merged**
